version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports: '3000:3000'
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_NAME=vendora
      - DB_DATABASE_TYPE=mysql
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      DB_PASSWORD: ''
      MYSQL_DATABASE: vendora
    ports:
      - '3306:3306'
